### ISSUE TITLE
issue in line 80, 81

### ISSUE THREAD

**Issue by PyroSage** [IsaacAsante/HackerRank#1]
in line 80:
```
else {
                if (extract != "=") {
                    // It's definitely an attribute name
                    attr_name = curr + "~" + extract;
                }
            }
```
we can use the else if statement directly, also there should extract[0] not just extract
```
else if (extract[0] != '=')
```

**Comment by IsaacAsante** [comment]
Hi @Maxikun can you specify which exact file in this repo you are referring to?

**Comment by PyroSage** [comment]
> Hi @Maxikun can you specify which exact file in this repo you are referring to?

Attribute parser in the C++ folder

**Comment by IsaacAsante** [comment]
> > Hi @Maxikun can you specify which exact file in this repo you are referring to?
> 
> Attribute parser in the C++ folder

If "extract" is a single character or a string (which is easy to compare with another string), then it's unnecessary to have extract[0]. Also, I just ran my code again on HackerRank, and it passed all the test cases. So, I'll close this issue since there's no fix needed. But if you find anything erroneous in the rest of the code on this repo, feel free to open a new issue, and I'll look into it.
